name: Push
run-name: ${{ github.ref_name }} push run 🚀
on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
      - 'release/**'
      - test-actions
    tags:
      - '*'
permissions:
  contents: write
jobs:
  create-appcast:
    name: Create Sparkle Appcast 🎙️
    runs-on: macos-26
    strategy:
      fail-fast: false
      matrix:
        target: [arm64, x86_64]
    defaults:
      run:
        shell: zsh --no-rcs --errexit --pipefail {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set Up Environment 🔧
        id: setup
        run: |
          : Set Up Environment 🔧
          if (( ${+RUNNER_DEBUG} )) setopt XTRACE

          local channel='stable'
          if [[ ${GITHUB_REF_NAME} == *(beta|rc)* ]] {
            channel='beta'
          }

          local -A arch_names=(x86_64 intel arm64 apple)
          print "cpuName=${arch_names[${{ matrix.target }}]}" >> $GITHUB_OUTPUT
          #print "commitHash=${GITHUB_SHA:0:9}" >> $GITHUB_OUTPUT
          print "commitHash=2396e6e9b" >> $GITHUB_OUTPUT
          print "channel=${channel}" >> $GITHUB_OUTPUT

          #local workflowRunId="$(gh run list --branch "${GITHUB_REF_NAME}" --event push --limit 1 --json "databaseId" --jq ".[].databaseId")"
          local workflowRunId="28768124637"
          print "workflowRunId=${workflowRunId}" >> $GITHUB_OUTPUT

      - name: Download Artifact 📥
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: obs-studio-macos-${{ matrix.target }}-${{ steps.setup.outputs.commitHash }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.setup.outputs.workflowRunId }}
